replicaCount: 1

image:
  repository: 720553586724.dkr.ecr.eu-west-3.amazonaws.com/eks-argocd-app
  tag: "d96e660a78e157461c590a249de4d275f54cf539"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
